name: Trigger auto deployment for container-app-gn3e3ldka2cdg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-gn3e3ldka2cdg-AutoDeployTrigger-8d26b19d-704b-4f9e-9973-1a43909ad76b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGN3E3LDKA2CDG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGN3E3LDKA2CDG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGN3E3LDKA2CDG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGN3E3LDKA2CDG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGN3E3LDKA2CDG_REGISTRY_PASSWORD }}
          containerAppName: container-app-gn3e3ldka2cdg
          resourceGroup: djangoappspaces94e1bd3a
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


